version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpass
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
